SM:
  - -0.1598998512763587
  - 0.1308030905446035
  - 0.06105150239348626
  - -0.08039584764634908
  - 0.16873029204122
  - 0.9156098557840342
  - 0.09356346327088733
  - 0.71276950306391
  - 1.87768578450471
bias:
  - 0.2884138476939466
  - 4.761100967334946
  - 9.75278846984968